[package]
name = "sierra_u128_range_checked_contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.14.0"

[[target.starknet-contract]]
sierra = true
casm = false

[profile.dev.cairo]
inlining-strategy = "default"

[profile.release.cairo]
inlining-strategy = "default"
