[package]
name = "newton_u128_cairo_baseline"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.14.0"

[cairo]
enable-gas = true

[dev-dependencies]
cairo_test = "2.14.0"

[[target.lib]]

[[target.starknet-contract]]
sierra = true
casm = false
